### ISSUE TITLE
document / improve open drone maps compatibility

### ISSUE THREAD

**Issue by balthazarneveu** [wisescootering/infrareddrone#10]
https://github.com/OpenDroneMap/ODM
Using docker , it will run correctly ... 
`docker run -ti --rm -v FLY-test:/datasets/code opendronemap/odm --project-path /datasets --cameras /datasets/code/cameras_nodist.json --orthophoto-resolution 4.`

Put camera_nodist.json at the root so you open drone map will not re-d
```
{
    "dji fc3170 3892 2892 brown 0.6666": {
        "projection_type": "brown",
        "width": 3892,
        "height": 2892,
        "focal_x": 0.6654633618550062,
        "focal_y": 0.6654633618550062,
        "c_x": -0.004680156368913146,
        "c_y": -0.0037616129545701956,
        "k1": 0.0,
        "k2": 0.0,
        "p1": 0.0,
        "p2": 0.0,
        "k3": 0.0
    }
}

```

![image](https://user-images.githubusercontent.com/41070742/159187802-460bb1de-82dc-47aa-88cd-929f4881e6a0.png)

WARNING: your images needs to be in a folder named **images**

Then you can use  **QGIS** 
https://www.qgis.org/fr/site/forusers/download.html
Open  **FLY-test/odm_orthophoto/odm_orthophoto.tif**

To add Google maps / satellite Hybrid , (refer to this tutorial https://www.youtube.com/watch?v=7X4KogKh_pQ)

![image](https://user-images.githubusercontent.com/41070742/159187837-b030f98a-9203-4464-b687-5734fd557650.png)
```
Google Maps: https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}
Google Satellite: http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}
Google Satellite Hybrid: https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}
Google Terrain: https://mt1.google.com/vt/lyrs=t&x={x}&y={y}&z={z}
Google Roads: https://mt1.google.com/vt/lyrs=h&x={x}&y={y}&z={z}
```

🇫🇷 It's possible to use IGN aswell . Follow the instructions here 
https://geoservices.ign.fr/services-web-decouverte
![image](https://user-images.githubusercontent.com/41070742/159188389-ae990440-310f-4340-bdba-bd80cefba20a.png)

**Comment by balthazarneveu** [comment]
@Neveu-Alain 
- Test  if QGIS alignment improve if we copy absolute altitude into exif GPS in IRd.summaryFlight   -> Image instances modify gps dict & altitude in Fly
- Update command line options for ODM
- Retest 3x stitching stability for VIS , NIR and VIR to see if QGIS **Result =  Not perfectly aligned**

**Comment by balthazarneveu** [comment]
After processing is finished:
- Select images , move or copy into a dedicated visProject/images ,  nirProject/images   folders
- Create a .bat for each so docker is launched for ODM in a single click

**Comment by Neveu-Alain** [comment]
`docker run -ti --rm -v C:\Air-Mission\FLY-20220125-Test:/datasets opendronemap/odm --project-path /datasets mapping-VIR-force-gps --cameras /datasets/cameras/camera_IRdrone.json --orthophoto-resolution 1. --ignore-gsd  --fast-orthophoto --force-gps`

**Comment by balthazarneveu** [comment]
.bat  + folder with odm content is now automatically created. 
Remaining TODO : pick optimal overlapping with less images

**Comment by balthazarneveu** [comment]
Optimal overlap according to @Neveu-Alain  is 1/9th of the 1/3rd best synchronized images

**Comment by balthazarneveu** [comment]
**DISCARDED IDEA**
use ODM with multisprectral feature 
It seems like renaming images according the following page https://docs.opendronemap.org/fr/multispectral/ could allow dealing with multispectral images.
https://github.com/OpenDroneMap/ODM/blob/master/opendm/photo.py#L273-L386 It's not easy to modify xmp though ...
