### ISSUE TITLE
Cohérence données EXIF

### ISSUE THREAD

**Issue by AlainNeveu** [wisescootering/infrareddrone#23]
A PROPOS DE LA COHERENCE DES DONNES EXIF DANS IRDrone v1.2.
______________________________________________________________________________________________
1 - DE QUOI PALE T-ON?:

IRdrone génère des images VIS, NIR, VIR et NDVI au format jpg qui n'ont pas de données Exif natives.

Ces images sont issues du traitement d'un couple "maitre" d'images prises par des caméras différentes:
- DJI. Spectre visible (VIS). Format DNG.
- SJCam M20 spectre proche infrarouge (NIR). Format "RAW" et JPG. 
L'image DJI-DNG possède des données EXIF. 
Il n'y a pas de métadonnées pour l'image au format RAW de la SJCam. Elles sont disponibles dans les fichiers au format jpg et dng.
Cependant on remarque que la date de l'image au formaut dng est la même que celle au foramt jpg.
Ceci est anormal puisque les dng sont enregistrées toutes les 3s au "top" du timelapse alors que les jpg sont enregistrées 2s après. 
Par exemple 2022_0125_130916_203.dng a ét prise  à 13h 09min 16s  alors que la métadonnée exif indique Date/Time Original: 2022:01:25 13:09:18 
Cette date est celle de l'enregistrement de l'image jpeg associée 2022_0125_130918_204.JPG
que ... heureusment le nom du fichier dng contient la date!

On peut visualiser ces métadonnées avec exiftool.

Les images produites sont construites en alignant l'image NIR de la SJcam sur l'image VIS du DJI, puis par mélange des canaux des bandes spectrales. 
Les données les plus pertinantes seraient donc celles fournies par le DJI.
 
En particulier les métadonnées du DJI comprennent :

 > le fabricant,le type de caméra, le type d'optique (Lens Model)
	Make                            : DJI
	Camera Model Name               : FC3170
 > la taille de l'image (en pixels) et son orientation
	Image Width                     : 4000
	Image Height                    : 3000
   	Orientation 			: Horizontal (normal)
 > les distances focales
	Focal Length                    : 4.5 mm
	Focal Length In 35mm Format     : 24 mm
 >  le temps d'exposition et  l'ouverture 	
	Exposure Time                   : 1/240
	F Number                        : 2.8                   
 et aussi
 > la date de prise de vue 
	Date/Time Original              : 2022:01:25 12:04:24 
 > les coordonnées GPS (Altitude, Longitude Longitude)
 > l'attitude du drone et de la caméra ( Gimbal & Flight Pitch, Yaw, Roll )
	
 
En vue d'un post traitement, par exmple avec Open Drone Mapping (ODM) il est nécessaire d'affecter aux images générées par IRdrone des données EXIF. 
Toutefois les images originales du drone et de la caméra infrarouge sont corrigées en fonction des données de calibration. 
En particulier la distance focale utilisée est différente de celle donnée par l'exif des images DNG de la caméra du drone. Cela modifie le FOV. 
De plus les images sont rognées ce qui modifie aussi le FOV.
On ne peut donc pas utiliser directement les métadonnées de l'image du drone sous peine d'incohérences. 

Par exemple ODM utilise la taille de l'image et un paramètre de focale dans son fichier camera.json. 
ODM calcul ces paramètres en fonction des métadonnées des images à traiter.
ODM vérifie si ils sont compatibles avec les paramètres du fichier camera\camera.json  (ce fichier est une option de la CIL odm_mapping.bat).
Si les paramètres sont incompatibles ODM genère son propre fichier cameras.json!
Dans ce cas si la caméra est rconnues par ODM celui çi applique des coefficients de distorsion "standards".
Ces coefficients existent manifestement pour notre caméra "dji fc3170".
Mais les images à traiter ont déjà été redressées par IRdrone, et de plus avec des coefficients de distorsion spécifique à notre matériel.
Donc appliquer de nouveau la distorsion serait incohérent.

______________________________________________________________________________________________
2- EN PRATIQUE 

On utilise les formules suivantes:

taille du pixel			dpix = 0,0016	  mm	| valeur doc DJI)
largeur image 35mm		lx_35mm = 36	  mm	| format 24x36     Wikipédia )
focale calibration		fpix_IRd = 2898,5 pix   | mesure de la focale provenant de la calibration)
nb pixels horizontaux		Nx_Ird = 3892	  pix	| Correspond aux images "croppées" par IRdrone)
nb pixels verticaux		Ny_IRD = 2892	  pix	|
	
Focal Length			fIRd = fpix_IRd * dpix  						( mm )
Focal Length In 35mm Format	fIRd35mm = fpix_Calibration * lx_35mm/Nx_Ird   				( mm )         
Scale Factor			Sc = fIRd_35mm/fIRd
Field of view			FOV_IRd	= DEGRES(2*ATAN(lx_35mm/(2*fIRd_35mm)))				( ° )  
Facteur k			k_IRD = fIRd_35mm/lx_35mm = =1/(2*TAN(RADIANS(FOV_IRd/2)))

numériquement on trouve    	
	
fIRd = 4,6	mm	  	Valeur arrondie pour utilisation dans l'EXIF
fIRd35mm = 27	mm		Valeur arrondie pour utilisation dans l'EXIF.
Sc = 5,9	[-]		Cette valeur est calculée automatiquement par exiftool
FOV_IRd = 67,4	 °		Valeur arrondie (à la première décimale)calculée automatiquement par exiftool
k_IRD = 0,75	[-]		Valeur arrondie (à la première décimale) calculée par odm dans camera.json

Avec ces formules on retrouve bien toutes les paramètres donnés par exiftool.
Certains de ces paramètres sont manifestement calculés par exiftool. Par exemple le FOV, le "scale factor" ou l'hyperfocale.

______________________________________________________________________________________________
3- CONCRETEMENT :
> écrire pour chaque image générée par IRdrone des métadonnées EXIF spécifiques. 

	Make                            : irdrone
	Camera Model Name               : multispectral
	Lens Model                      : 850nm             (selon le type de filtre NIR monté sur la SJCam)
	Image Width                     : 3892
	Image Height                    : 2892
   	Orientation 			: Horizontal (normal)
	Focal Length                    : 4.6 mm
	Focal Length In 35mm Format     : 27 mm
	F Number                        : idem DNG du DJI
	Date/Time Original              : idem DNG du DJI
        --------------------------------------------------------------------------------------------------------
	Absolute Altitude               : Celle calculée via l'API IGN
	GPS Version ID                  : idem DNG du DJI
	GPS Latitude Ref                : idem DNG du DJI
	GPS Longitude Ref               : idem DNG du DJI
	GPS Altitude Ref                : Above Sea Level
	GPS Latitude                    : 45 deg 10' 10.37" N
	GPS Longitude                   : 3 deg 24' 0.06" E		  
	---------------------------------------------------------------------------------------------------------	
	Relative Altitude               : idem DNG du DJI
	Gimbal Roll Degree              : idem DNG du DJI
	Gimbal Yaw Degree               : idem DNG du DJI
	Gimbal Pitch Degree             : idem DNG du DJI
	Flight Roll Degree              : idem DNG du DJI
	Flight Yaw Degree               : idem DNG du DJI
	Flight Pitch Degree             : idem DNG du DJI

> placer dans chaque dossier de mapping pour ODM (par exemple pour C:\Air-Mission\FLY-20220524-Thaumiers-Vol1\mapping_VIR__local)
    - le fichier camera\camera_IRdrone.json 
{
    "irdrone multispectral 3892 2892 brown 0.75": {
        "projection_type": "brown",
        "width": 3892,
        "height": 2892,
        "focal_x": 0.75,
        "focal_y": 0.75,
        "c_x": 0.0,
        "c_y": 0.0,
        "k1": 0.0,
        "k2": 0.0,
        "p1": 0.0,
        "p2": 0.0,
        "k3": 0.0
    }
}
  - le fichier odm_mapping.bat   

docker run -ti --rm -v C:/Air-Mission/FLY-20220524-Thaumiers-Vol1:/datasets opendronemap/odm 
		--project-path /datasets mapping_VIR__local 
		--cameras /datasets/mapping_VIR__local/camera/camera_IRdrone.json 
		--orthophoto-resolution 1.0 
		--ignore-gsd 
		--orthophoto-kmz 
		--fast-orthophoto 
		--force-gps 
		--use-exif
		--orthophoto-png
		--orthophoto-kmz

Rem 1:  L'option --orthophoto-kmz permet de voir l'image directement dans Google Earth.
Rem 2: 	Pour les tests rapides j'ai modifié avec ExifToolGUI les données Exif des images VIR pour le mapping ODM.
        et cela fonctionne parfaitement. En utilisant les formules précédentes tout est cohérent :-))

______________________________________________________________________________________________
4- CE QUI EXISTE dans la version 1.2:

> Un bloc de métadonnées de référence issu d'une image DNG du DJI est collé dans chaque image générée par IRdrone
> Les coordonnées GPS de ce bloc sont modifiées pour lui affecter la latitude et la longitude de l'image DJI du couple "maitre" (DJI-DNG/SJCam-RAW).
L'altitude GPS peut être par rapport au takeoff, au sol au niveau de la mer (calcul via l'API IGN) 
Le choix de l'altitude est controlé par une option dans IRdrone.
Attention le paramètre "GPS Altitude Ref" reste toujours à la valeur originale "Above Sea Level" (qui est incohérente puisque l'original indique l'altitude par rapport au takeoff!)
> les dates de prise de vue, les paramètres d'exposition NE SONT PAS MIS à jour
> les métadonnées d'attitudes du drone  sont stockées dans des fichiers HPERLAPSE_XXXX.exif dans le dossier AerialPhotography.
Par exemple: {"Gimbal Roll": 0.0, "Gimbal Yaw": -78.9, "Gimbal Pitch": -90.0, "Flight Roll": 0.1, "Flight Yaw": -80.4, "Flight Pitch": 2.5}

> Pour ODM pour chaque type de représentation (VIS, NIR, VIR, NDVI) un fichier camera.json est généré ainsi qu'une liste d'images 
	 
______________________________________________________________________________________________
5- RESTE A FAIRE pour la version 1.3:

> Récupérer toutes les données Exif utiles de chaque image du couple "maître" et les placer dans les fichiers .exif sous forme de dictionnaire (et lisible ?) 
> Dans les métadonnées Exif des images générées par IRdrone (à faire dans le "flot" du process ? plutôt qu'en post traitement)
	pour toutes les images:
	- Changer les valeurs de : "Make", "Camera Model", "Image Width", "Image Height", "Focal Length", "Focal Length In 35mm Format"
	- Ajouter "Lens Model"
 	- Modifier  "GPS Altitude Ref" (si c'est possible !)

	et pour chaque point de prise de vue:
       	- Affecter la "Date/Time Original"  de l'image DJI maître.
       	- Affecter les paramètres d'exposition de l'image DJI maître.
       	- Affecter les paramètres d'attitude du drone  ( pourrait être utile dans certains post traitement)
> Vérifier le contenu du fichier camera.json  (make, dim image, facteur k ...)

**Comment by AlainNeveu** [comment]
Ecriture des données Exif des images générées par IRdrone à l'aide d'ExifTool.
Une grande partie des données nécessaire peuvent être héritées des données EXIF de l'image originale (spectre visible) prise par le drone DJI au format DNG.
En particulier l'heure de prise de vue, l'attitude du drone, les coordonnées GPS, l'ouvertue et le temps de pose.
En revanche il est impératif de modifier les distances focales (réelle et equivalente) dont dépend le calcul du FOV, du scale factor etc.
En effet comme déjà expliqué les images générées par IRdrone correspondent à une focale qui tient compte de la focale calibrée (différente de la focale standard) et du rognage final de l'image.



Liste de options de la commade -TagsFromFile  utiles pour modifier les tags.

Commande typique: exiftool -TagsFromFile "sourcefile" -keyTag1=valueTag1 -keyTag2=valueTag2 ... "destinationfile" -overwrite_original

=============================================================================================================================== 

>Caméra (appareil virtuel produisant les images IRdrone)
	-Exif:Make=irdrone    (equivalent à -Make=irdrone  )   	*lu par ODM dans le fichier camera/camera_IRdrone.json
	-Exif:Model=multispectral				*lu par ODM
	-UniqueCameraModel=irdrone/multispectral
	-CameraModel=DJI-Mavic-Air2/SJCam-M20  (XMP-xmpDM)

> Optique (permet de garder une trace du filtre infrarouge utilisé)
	-Lens=850
	-LensModel=850nm/NIR/Kolarivision

> Distances focales (tenant compte de la focale calibrée du DJI et du cropde IRDrone):
	-Exif:FocalLenght=4.6
	-Exif:FocalLengthIN35mmFormat=27			*lu par ODM pour calculer focal_x & focal_y
	-Exif:LensInfo=27mm/f2.8   ATTENTION doit être cohérent avec Exif:FocalLengthIN35mmFormat

> Auteur et copyright. 
	-Artist=Flo
	-Author=Florine_Pepin
	-Copyright=BE-Pepin/Hugonot

> Format de l'image
	-Format=image/jpg    (XMP-dc)

> Attitude du drone  (XMP-drone-dji   (Ces données peuvent être modifiées au besoin ... )
	-AbsoluteAltitude=+1.00
	-CamReverse=0
	-FlightPitchDegree=+0.80
	-FlightRollDegree=-0.60
	-FlightYawDegree=-17.10
	-GimbalRevese=0
	-GimbalPitchDegree=-89.90
	-GimbalRollDegree=+0.00
	-GimbalYawDegree=-22.70
	-RelativeAltitude=+1.00
	-SelfData

> GPS
	-GPSVersionID=2.3.0.0
	-GPSLatitudeRef=North
	-GPSLatitude=45°44.7296
	-GPSLongitudeRef=East
	-GPSLongitude=2°3.9531
	-GPSAltitudeRef=AboveSeaLevel
	-GPSAltitude=1 m

=======================================================================================================

EXEMPLE d'un fichier .bat pour passer les commandes ExifTool.
___________________________
C:\Documents-Alain\Projet-IRdrone\Exif\exiftoolgui\exiftool.exe -TagsFromFile "C:/Air-Mission/toto/HYPERLAPSE_0048.DNG"  "C:/Air-Mission/toto/NoExif.jpg" -overwrite_original
C:\Documents-Alain\Projet-IRdrone\Exif\exiftoolgui\exiftool.exe -TagsFromFile "C:/Air-Mission/toto/NoExif.jpg" -Exif:FocalLengthIN35mmFormat=27 -Exif:FocalLength=4.6 -Exif:LensInfo=27mm/f2.8 -Author=Florine -Artist=FLO -Copyright=BE-Pepin/Hugonot -Lens=850 -LensModel=850nm/NIR/Kolarivision -Exif:Make=irdrone -Exif:Model=multispectral -CameraModel=DJI-Mavic-Air2/SJCam-M20 -UniqueCameraModel=irdrone/multispectral -Format=image/jpg  "C:/Air-Mission/toto/NoExif.jpg" -overwrite_original
_________________________

> La première ligne recopie les données Exif de l'image originale du DJI au format DNG dans l'image au format jpg générée par IRDrone. 
A noter que les dimensions de l'images sont corrigées automatiquement par ExifTool (on passe de 4000x3000 à 3892x2892)
> La deuxième ligne modifie les tags individuellement dans l'image au format jpg générée par IRDrone.


CE QUI RESTE A FAIRE: Basculer cette commande dans le code Python en récupérant 
 > la focale calibrée (en pixel), les dimensions du rognage (en pixel) ce qui permet de calculer les bonnes focales.
 > la longueur dde coupure du filtre NIR (renseignée dans le fichier Excel de la mission)
 > les noms des auteurs, copyright  mais c'est cosmétique!

Remarque: Le fait de changer le "Make" et le "Model" de la caméra évite que certains logiciels qui ont des bases de données (ODM, PhotoLab  etc) n'appliquent automatiquement des corrections.

**Comment by balthazarneveu** [comment]
1. Since  https://github.com/wisescootering/infrareddrone/commit/d2924f57d6485b957b840eea6633639328dca77b we copy the original metadata from the DJI dng file (including original gps, gimbal info).
2. By using `--use-fixed-camera-params` by default in ODM , we bypass camera calibration on the fly estimation in ODM , no matter what's inside the EXIF. **This means that the forced camera calibration file needs to be "perfect!"** https://github.com/wisescootering/infrareddrone/blob/master/odm_data/dji_fc3170.json as there won't be refinement. 

What we could do is still modify the exif files to overwrite the rough dji initial focal length by out  right modified focal length  & still allow ODM to perform its refinement during bundle adjustment.

**Comment by balthazarneveu** [comment]
@AlainNeveu  @Neveu-Alain  Please make a single call to exif tool in `copy_metadata`
