### ISSUE TITLE
option ODM pour accélérer l'affichage dans Qjis

### ISSUE THREAD

**Issue by AlainNeveu** [wisescootering/infrareddrone#26]
l'option ODM   --build-overviews  construit des images "basse" résolution (1/2, 1/4, 1/8, 1/16  de la résolution)  de l'image odm_orthophoto.tif. 
Ces images sont intégrées directement dans le fichier odm_orthophoto.tif.tif

Certains logiciels reconnaissent ces images à plus faible résolution et les utilisent pour accélérer l'affichage. C'est le cas de Qjis.
Ceci permet d'accélérer nettement la vitesse l'affichage en fonction du niveau de zoom.

**Comment by balthazarneveu** [comment]
Bien vu , on va rajouter l'option!


```
cmd += " --build-overviews"
if extra_suggested_options:
        cmd += " --smrf-threshold 0.3 --smrf-scalar 1.3 --smrf-slope 0.05 --smrf-window 24"
        # our goal is orthophoto, using parameters to increase the planarity attempt
        # illustrations in the odm missing guide -> pages 107/108/109
        cmd += " --texturing-skip-global-seam-leveling"
```
