### ISSUE TITLE
Images NIR dans le dossier ImgIRdrone

### ISSUE THREAD

**Issue by AlainNeveu** [wisescootering/infrareddrone#30]
Avec l'option `'--odm-multispectral'` ce serait bien de remettre l'image alignée NIR_local au format .jpg  dans le dossier `.../dirMission/ImgIRdrone` (à coté du `redo.bat` associé à cette image). 
Cela permettrait de voir si elle est bien alignée ou si elle a eu un problème.
L'image VIR.jpg est moins précise pour cet objectif de contrôle visuel car la bande spectrale proche infrarouge (NIR) qui pourrait être mal alignée est placée sur la couche Red alors que les couches Green  et Blue proviennent respectivement des couches Red et Green de l'image dans le spectre visible (VIS). Ces deux couches semble l'emporter dans le cas d'un petit défaut d'alignement.

**Comment by balthazarneveu** [comment]
### Trace mechanism through command lines options
Added option to specify which traces you'd like to see in the output folder.
```
--traces {vis,nir,vir,ndvi} [{vis,nir,vir,ndvi} ...]
                        export specific spectral traces
```

- in case **`--odm-multispectral`** is not specified, If no argument is provided , all traces are exported by default (old behavior)
- in case **`--odm-multispectral`** is specified, 
1/ If no  `--traces` argument is provided , only VIR is exported.  -> this it the default behavior you request in the message above @AlainNeveu 
2/ If `--traces` argument is provided , selected traces are exported.


### Solving the manual modifications in case of multispectral...

- [x] do not force XXXX_1.tif but rather the original naming 0001_1.tif should be HYPERLAPSE_102_1.tif 
- [x] support multispectral_folder in `automatic_registration.py` so REDONE images can be reprocessed correctly

If I perform a "REDO.bat" and forcing a really bad initial alignment
![image](https://user-images.githubusercontent.com/41070742/196041302-41bb9406-f0ed-4e37-ae6e-c8999345e589.png)

I can see the multispectral folder being updated with the new NIR manually aligned tif.
![image](https://user-images.githubusercontent.com/41070742/196041278-67664382-0540-436e-a343-0d852b503c92.png)
